In [1]:
import numpy as np

In [2]:
data = np.random.randn(2,3)
data

array([[ 0.97642699,  0.9973839 ,  0.14208557],
       [-0.61009188, -0.0635262 ,  0.01749296]])

In [3]:
data * 10

array([[ 9.7642699 ,  9.97383895,  1.42085573],
       [-6.10091881, -0.63526196,  0.1749296 ]])

In [4]:
data + data

array([[ 1.95285398,  1.99476779,  0.28417115],
       [-1.22018376, -0.12705239,  0.03498592]])

In [5]:
data.dtype

dtype('float64')

In [6]:
data.shape

(2, 3)

In [7]:
# creating arrays from sequences or zeros or ones or empty
# default type is float64
d1 = [[1,2,3,4],[4,5,6,7]]
arr2 = np.array(d1)
arr2

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [8]:
arr2.ndim

2

In [9]:
arr2.shape

(2, 4)

In [10]:
arr2.dtype

dtype('int32')

In [11]:
np.zeros((2,3)) # for 2x3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
np.ones((2,3)).astype("str")

array([['1.0', '1.0', '1.0'],
       ['1.0', '1.0', '1.0']], dtype='<U32')

In [12]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.empty((2,10)) # garbage vals

array([[2.12199579e-314, 4.24399158e-314, 4.24399158e-314,
        9.88131292e-324, 1.42413555e-306, 1.78019082e-306,
        1.37959740e-306, 6.23057349e-307, 1.02360935e-306,
        1.69120416e-306],
       [1.78022342e-306, 6.23058028e-307, 1.06811422e-306,
        9.45699680e-308, 1.11258854e-306, 1.11261502e-306,
        1.42410839e-306, 7.56597770e-307, 6.23059726e-307,
        1.42419530e-306]])

In [14]:
np.arange(7,0,-1) # like range

array([7, 6, 5, 4, 3, 2, 1])

In [33]:
np.full((2,3),4)

array([[4, 4, 4],
       [4, 4, 4]])

In [15]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [16]:
arr1 = np.array([1,2,3] , dtype='float64')
arr1

array([1., 2., 3.])

In [17]:
# type casting
float_arr = np.array([1.1,2.4,-4.5])
float_arr

array([ 1.1,  2.4, -4.5])

In [18]:
float_arr.astype(np.int64)

array([ 1,  2, -4], dtype=int64)

In [19]:
np.array(["2.2","4.5","-6.77"]).astype(float)

array([ 2.2 ,  4.5 , -6.77])

In [35]:
a1 = np.random.randn(2,4)
a1

array([[ 0.19158209,  0.26712657,  1.13732476,  0.24364163],
       [ 0.07014385, -0.36822615,  1.26061618,  0.73239401]])

In [36]:
a2 = a1.copy()
a2[1,2] = 29
a2

array([[ 0.19158209,  0.26712657,  1.13732476,  0.24364163],
       [ 0.07014385, -0.36822615, 29.        ,  0.73239401]])

In [37]:
a1

array([[ 0.19158209,  0.26712657,  1.13732476,  0.24364163],
       [ 0.07014385, -0.36822615,  1.26061618,  0.73239401]])