In [2]:
import numpy as np

In [3]:
data = np.random.randn(2,3)
data

array([[-0.01391734,  1.51873741,  0.17607388],
       [ 0.00804525, -0.62194596,  0.75987086]])

In [4]:
data * 10

array([[-0.13917337, 15.18737409,  1.76073875],
       [ 0.08045249, -6.21945955,  7.59870856]])

In [5]:
data + data

array([[-0.02783467,  3.03747482,  0.35214775],
       [ 0.0160905 , -1.24389191,  1.51974171]])

In [6]:
data.dtype

dtype('float64')

In [7]:
data.shape

(2, 3)

In [8]:
# creating arrays from sequences or zeros or ones or empty
# default type is float64
d1 = [[1,2,3,4],[4,5,6,7]]
arr2 = np.array(d1)
arr2

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [10]:
arr2.ndim

2

In [11]:
arr2.shape

(2, 4)

In [17]:
arr2.dtype

dtype('int32')

In [15]:
np.zeros((2,3)) # for 2x3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.empty((2,10)) # garbage vals

array([[9.24661010e-312, 5.73116149e-322, 0.00000000e+000,
        0.00000000e+000, 1.42413554e-306, 3.16251369e+180,
        1.05776693e-153, 6.03461190e+151, 1.17631271e-095,
        1.67772392e+243],
       [1.16466606e-028, 4.90900643e+252, 1.94918511e-153,
        1.16568549e+253, 7.49511203e+247, 1.12284826e+219,
        1.94919754e-153, 8.76730942e+252, 2.59903831e-144,
        1.42419596e-306]])

In [19]:
np.arange(7,0,-1) # like range

array([7, 6, 5, 4, 3, 2, 1])

In [20]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [21]:
arr1 = np.array([1,2,3] , dtype='float64')
arr1

array([1., 2., 3.])

In [22]:
# type casting
float_arr = np.array([1.1,2.4,-4.5])
float_arr

array([ 1.1,  2.4, -4.5])

In [23]:
float_arr.astype(np.int64)

array([ 1,  2, -4], dtype=int64)

In [26]:
np.array(["2.2","4.5","-6.77"]).astype(float)

array([ 2.2 ,  4.5 , -6.77])