In [2]:
import numpy as np

In [3]:
arr2d = np.arange(12).reshape((3,4))
arr2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
arr2d[1:,2]

array([ 6, 10])

In [5]:
arr2d[:,:2]

array([[0, 1],
       [4, 5],
       [8, 9]])

In [6]:
arr2d[2:4, :2]

array([[8, 9]])

In [9]:
arr = np.arange(20).reshape((4,5))
arr[:]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [10]:
arr[2:4,3]

array([13, 18])

In [20]:

# Important bheski : adds dimension
print(arr[:,:1]) #shape (4,1)
print(arr[:,0]) #shape (4,)
print(arr[1:2,:2])

[[ 0]
 [ 5]
 [10]
 [15]]
[ 0  5 10 15]
[[5 6]]


In [34]:
arr
names = np.array(["chica" , "freddy" , "foxy" , "bonnie"])
print(arr[(names == "chica")])
print(arr[~(names == "chica")]) #negate with ~ or (! in  condition)

[[0 1 2 3 4]]
[[ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [37]:
bool_arr = np.array([0,1,0,0,1,0]).astype(bool)
bool_arr

array([False,  True, False, False,  True, False])

In [38]:
~bool_arr

array([ True, False,  True,  True, False,  True])

In [39]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [46]:
arr[arr > 4] = 0
arr

array([[0, 1, 2, 3, 4],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [56]:
# Fancy indexing - copying
arr = np.arange(6).reshape((3,2
))
arr

array([[0, 1],
       [2, 3],
       [4, 5]])

In [55]:
arr[[1,0]][:, [0]]

array([[2],
       [0]])

In [58]:
# Transposing
arr

array([[0, 1],
       [2, 3],
       [4, 5]])

In [59]:
arr.T

array([[0, 2, 4],
       [1, 3, 5]])